
.\" Manpage for mooOS.
.\" Contact pdq@localhost
.TH man 8 "August 12 2013" "0.1" "mooOS man page"
.SH NAME
mooOS \- keybinds for mooOS GNU/Linux and Arch Linux (e18/vimb)
.SH SYNOPSIS
too much to list
.SH DESCRIPTION
mooOS is a GNU/Linux distribution based on Arch Linux
.SH KEYBINDS - enlightenment
.
.br
KP_Delete                  Previous Window
.
.br
KP_Insert                  Next Window
.
.br
KP_Substract               Command: /usr/bin/sub3
.
.br
Alt + F1                   Switch to Desktop 0
.
.br
Alt + F2                   Switch to Desktop 1
.
.br
Alt + F3                   Switch to Desktop 2
.
.br
Alt + F4                   Switch to Desktop 3
.
.br
Alt + F5                   Switch to Desktop 4
.
.br
Alt + F6                   Switch to Desktop 5
.
.br
Alt + F7                   Switch to Desktop 6
.
.br
Alt + F8                   Switch to Desktop 7
.
.br
Alt + F9                   Switch to Desktop 8
.
.br
Alt + F10                  Switch to Desktop 9
.
.br
Alt + F11                  Switch to Desktop 10
.
.br
Alt + F12                  Switch to Desktop 11
.
.br
Alt + Tab                  Next Window
.
.br
Alt + Escape               Show Everything Launcher
.
.br
Win + 1                    Switch to Desktop 1
.
.br
Win + 2                    Switch to Desktop 2
.
.br
Win + 3                    Switch to Desktop 3
.
.br
Win + 4                    Switch to Desktop 4
.
.br
Win + 5                    Switch to Desktop 5
.
.br
Win + 6                    Switch to Desktop 6
.
.br
Win + B                    Toggle Borderless State
.
.br
Win + F                    Fullscreen Mode Toggle
.
.br
Win + J                    Next Window
.
.br
Win + k                    Previous Window
.
.br
Win + L                    Lock
.
.br
Win + M                    Iconic Mode Toggle (minimize)
.
.br
Win + O                    Command: /usr/bin/dmenu_mocp -p "MUSIC:"
.
.br
Win + P                    Show Everything Launcher
.
.br
Win + S                    Sticky Mode Toggle
.
.br
Win + X                    Kill
.
.br
Win + Up                   Maximize
.
.br
Win + Down                 Lower
.
.br
Win + Left                 Maximize Left
.
.br
Win + Right                Maximize Right
.
.br
Win + Grave                Close
.
.br
Win + KP_End               Command: /usr/bin/dolphin
.
.br
Win + Return               Command: /usr/bin/terminology
.
.br
Win + KP_Down              Command: /usr/bin/firefox
.
.br
Win + Backspace            Close
.
.br
Win + Shift + Return       Command: /usr/bin/urxvtc
.
.br
Ctrl + Shift + Left        Send Mouse Back 1 Screen
.
.br
Ctrl + Shift + Right       Send Mouse Forward 1 Screen
.
.br
Alt + Shift + Left         Flip Desktop Left
.
.br
Alt + Shift + Right        Flip Desktop Right
.
.br
Ctrl + Alt + D             Show The Desktop
.
.br
Ctrl + Alt + End           Restart Enlightenment
.
.br
Ctrl + Alt + Up            Window Up
.
.br
Ctrl + Alt + Down          Window Down
.
.br
Ctrl + Alt + Left          Window on the Left
.
.br
Ctrl + Alt + Right         Window on the Right
.
.br
Ctrl + Alt + Shift + Left  To Previous Desktop
.
.br
Ctrl + Alt + Shift + Right To Next Desktop
.
.br
.SH SEE ALSO
vimb(1), vb(1), gh(1), pdq(1)
.SH BUGS
https://github.com/idk/mooOS/issues
.SH AUTHOR
pdq (pdq@localhost) 
