.\" Manpage for mooOS.
.\" Contact pdq@localhost
.TH man 8 "August 12 2013" "0.1" "mooOS man page"
.SH NAME
mooOS \- keybinds for mooOS GNU/Linux and Arch Linux (e18/vimb)
.SH SYNOPSIS
too much to list
.SH DESCRIPTION
mooOS is a GNU/Linux distribution based on Arch Linux
.SH KEYBINDS - enlightenment
.
.br
Ctrl + Alt + End           Restart Enlightenment
.
.br
.SH SEE ALSO
vimb(1), vb(1), gh(1), pdq(1)
.SH BUGS
https://github.com/idk/mooOS/issues
.SH AUTHOR
pdq (pdq@localhost) 
