#!/usr/bin/bash
## Part of mooOS-dev-tools - https://github.com/idk/mooOS-dev-tools
## pdq 08-13-2013 - PRESENT
## License: GPL3

## This script contains the mooOS-dev-tools functions

## generic yes/no function
ask_something() {
	echo -ne $question
	while read -r -n 1 -s yn; do
		if [[ $yn = [YyNn] ]]; then
			[[ $yn = [Yy] ]] && return=0
			[[ $yn = [Nn] ]] && return=1
			break
		fi
	done
	return $return
}

check_repos() {
	while true
	do
		if [ $2 -eq 1 ]; then
			torsocks curl -s -o "/dev/null" "$1"
		else
			curl -s -o "/dev/null" "$1"
		fi

		if [ $? -ne 0 ] ; then
			echo "Error occurred getting URL $1: rechecking in 10 seconds"
		elif [ $? -eq 6 ]; then
			echo "Unable to resolve host: rechecking in 10 seconds"
		elif [ $? -eq 7 ]; then
			echo "Unable to connect to host: rechecking in 10 seconds"
		else
			echo "$1 is UP! :D proceeding..."
			notify-send "$1 is UP! :D proceeding..." -i "$MOO_ICON"

			break
		fi
		sleep 10s
	done
}

create_packages_list() {
	question="${bldyellow}Run github sync? (Y/N)?\n${txtrst}"
	if ask_something; then
		pacman -Qqe  | grep -vx "$(pacman -Qqg base)" | grep -vx "$(cat ${MOO_HOME}github/mooOS-dev-tools/backup_exclude_pkgs)" > ${ARCHLIVE}archlive/releng/packages.both
		su -l $MOO_USER -c "gh -b"
	fi
}

do_system_updates() {
	question="${bldyellow}Run system updates? (Y/N)?\n${txtrst}"
	if ask_something; then
		question="${bldyellow}with --devel? (Y/N)?\n${txtrst}"
		if ask_something; then
			devel=" --devel"
		fi

		echo "${bldgreen}Applying i686 updates...${txtrst}"
		schroot -p -- sudo pacman -Syu && schroot -p -- pacaur -Syua$devel --noedit --rebuild
		notify-send "Applied i686 updates" -i "$MOO_ICON"
		echo "${bldgreen}Applying x86_64 updates...${txtrst}"
		sudo pacman -Syu && pacaur -Syua$devel --noedit --rebuild
		notify-send "Applied x86_64 updates" -i "$MOO_ICON"
	fi
}

create_custom_packages() {
	question="${bldyellow}Rebrand packages? (gh/vb-pdq/filesystem/grub/lsb-release/syslinux/hardinfo) (Y/N)?\n${txtrst}"
	if ask_something; then
		## sync ABS
		echo "${bldgreen}Syncing Arch Build System...${txtrst}"
		sudo abs

		## install custom mooOS packages
		## wallpapers
		# cd ${MOO_HOME}github/mooOS-wallpapers
		# makepkg -sf
		# schroot -p -- makepkg -sf

		## github wrapper
		delete_custom_package_caches "gh"
		mkdir -p ${MOO_HOME}abs/gh
		cd ${MOO_HOME}abs/gh
		wget https://raw.github.com/idk/gh/master/PKGBUILD
		makepkg -sf
		schroot -p -- makepkg -sf
		cd "$PWD"

		## vimb web browser and tabbed, patched!
		# delete_custom_package_caches "vb-pdq"
		# mkdir -p ${MOO_HOME}abs/vb-pdq
		# cd ${MOO_HOME}abs/vb-pdq
		# wget https://raw.github.com/idk/vb-pdq/master/PKGBUILD
		# wget https://raw.github.com/idk/vb-pdq/master/vb-pdq.install
		# makepkg -sf
		# schroot -p -- makepkg -sf

		## make custom branded packages

		## FILESYSTEM
		delete_custom_package_caches "filesystem"
		cp -r /var/abs/core/filesystem/ ${MOO_HOME}abs
		cp -vf ${MOO_HOME}github/mooOS-dev-tools/filesystem/issue ${MOO_HOME}abs/filesystem/
		cp -vf ${MOO_HOME}github/mooOS-dev-tools/filesystem/os-release ${MOO_HOME}abs/filesystem/
		FILESYSTEM_HASH=$(md5sum ${MOO_HOME}abs/filesystem/issue | awk '{print $1}')
		FILESYSTEM2_HASH=$(md5sum ${MOO_HOME}abs/filesystem/os-release | awk '{print $1}')
		sed -i "s/7813c481156f6b280a3ba91fc6236368/$FILESYSTEM_HASH/g" ${MOO_HOME}abs/filesystem/PKGBUILD
		sed -i "s/b16a4674ccf3a932ff34c6c8393a4f33/$FILESYSTEM2_HASH/g" ${MOO_HOME}abs/filesystem/PKGBUILD
		cd ${MOO_HOME}abs/filesystem
		makepkg -sf
		schroot -p -- makepkg -sf
		cd "$PWD"

		## LSB-RELEASE
		delete_custom_package_caches "lsb-release"
		cp -r /var/abs/community/lsb-release/ ${MOO_HOME}abs
		cp -vf ${MOO_HOME}github/mooOS-dev-tools/lsb-release/PKGBUILD ${MOO_HOME}abs/lsb-release/
		cp -vf ${MOO_HOME}github/mooOS-dev-tools/lsb-release/lsb-release.install ${MOO_HOME}abs/lsb-release/
		cd ${MOO_HOME}abs/lsb-release
		makepkg -sf
		schroot -p -- makepkg -sf
		cd "$PWD"

		## GRUB
		delete_custom_package_caches "grub"
		cp -r /var/abs/testing/grub ${MOO_HOME}abs/grub
		sed -i "s/\"Arch\"/\"MooOS\"/g" ${MOO_HOME}abs/grub/grub.default
		sed -i "s/Arch Linux/MooOS GNU\/Linux/g" ${MOO_HOME}abs/grub/grub.cfg
		GRUB_HASH=$(md5sum ${MOO_HOME}abs/grub/grub.default | awk '{print $1}')
		GRUB_HASH2=$(md5sum ${MOO_HOME}abs/grub/grub.cfg | awk '{print $1}')
		sed -i "s/a03ffd56324520393bf574cefccb893d/$GRUB_HASH/g" ${MOO_HOME}abs/grub/PKGBUILD
		sed -i "s/c8b9511586d57d6f2524ae7898397a46/$GRUB_HASH2/g" ${MOO_HOME}abs/grub/PKGBUILD

		cd ${MOO_HOME}abs/grub
		makepkg -sf
		schroot -p -- makepkg -sf
		cd "$PWD"

		## SYSLINUX
		delete_custom_package_caches "syslinux"
		cp -r /var/abs/core/syslinux/ ${MOO_HOME}abs
		sed -i "s/Arch Linux/MooOS GNU\/Linux/g" ${MOO_HOME}abs/syslinux/syslinux.cfg
		SYSLINUX_HASH=$(md5sum ${MOO_HOME}abs/syslinux/syslinux.cfg | awk '{print $1}')
		sed -i "s/46ca150f53322ff8f1597d9a342f7e40/$SYSLINUX_HASH/g" ${MOO_HOME}abs/syslinux/PKGBUILD
		cd ${MOO_HOME}abs/syslinux
		makepkg -sf
		schroot -p -- makepkg -sf
		cd "$PWD"

		## HARDINFO
		delete_custom_package_caches "hardinfo"
		cp -r /var/abs/community/hardinfo/ ${MOO_HOME}abs
		sed -i "s/Arch Linux/MooOS GNU\/Linux/g" ${MOO_HOME}abs/hardinfo/hardinfo.distro
		HARDINFO_HASH=$(sha1sum ${MOO_HOME}abs/hardinfo/hardinfo.distro | awk '{print $1}')
		sed -i "s/\"arch\"/\"mooos\"/g" ${MOO_HOME}abs/hardinfo/PKGBUILD
		sed -i "s/4c31cbbfbdeb48593641ff600c8d4fb7bda2b01c/$HARDINFO_HASH/g" ${MOO_HOME}abs/hardinfo/PKGBUILD
		cd ${MOO_HOME}abs/hardinfo
		makepkg -sf
		#TODO
		#schroot -p -- makepkg -sf
		cd "$PWD"
		notify-send "Rebranded packages" -i "$MOO_ICON"
	fi
}

delete_package_caches() {
	echo "${bldgreen}Deleting old packages cache...${txtrst}"
	#sudo pkgcacheclean -v 1
	schroot -p -- sudo pkgcacheclean -v 1
	sudo pkgcacheclean -v -k --cachedir=${ABS_BASE_DIR}mooOS-pkgs-32/ 1
	sudo pkgcacheclean -v -k --cachedir=${ABS_BASE_DIR}mooOS-pkgs-64/ 1
	sudo pkgcacheclean -v -k --cachedir=${MOO_HOME}abs/i686 1
	sudo pkgcacheclean -v -k --cachedir=${MOO_HOME}abs/x86_64 1
	mv ${ABS_BASE_DIR}mooOS-pkgs-32/*nvidia* ${ABS_BASE_DIR}nonfree/
	mv ${ABS_BASE_DIR}mooOS-pkgs-64/*nvidia* ${ABS_BASE_DIR}nonfree/
}

delete_custom_package_caches() {
	if [ "$1" != "" ]; then
		sudo rm -v ${ABS_BASE_DIR}mooOS-pkgs-32/$1-*
		sudo rm -v ${ABS_BASE_DIR}mooOS-pkgs-64/$1-*
		sudo rm -v ${MOO_HOME}abs/i686/$1-*
		sudo rm -v ${MOO_HOME}abs/x86_64/$1-*
		rm -fr ${MOO_HOME}abs/$1
	fi
}

rsync_iso_remote() {
	## sync .iso to remote server
	ARCH_ISO=$1

	question="${bldyellow}Sync md5sums and new names to website? (Y/N)?\n${txtrst}"
	if ask_something; then
		## create initial old hash
		if [ ! -f "${ABS_BASE_DIR}mooOS_${ARCH_ISO}.md5sum.old" ]; then
			su -l $MOO_USER -c "echo 53ef866dd48dcbd620cf402d845c2ec5 > ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.md5sum.old"
		fi

		echo "generating ${ARCH_ISO} md5sum... please wait a moment"
		# md5sums of current and old .iso
		MD5HASH=$(md5sum $ISO_DIR/*-${ARCH_ISO}*.iso | cut -d " " -f 1)

		## create initial current hash
		if [ ! -f "${ABS_BASE_DIR}mooOS_${ARCH_ISO}.md5sum" ]; then
			su -l $MOO_USER -c "echo $MD5HASH > ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.md5sum"
		fi

		CURMD5HASH=$(cat ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.md5sum)
		OLDMD5HASH=$(cat ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.md5sum.old)
		NEW=0
		## if new iso create hashes
		if [ "$CURMD5HASH" != "$MD5HASH" ]; then
			su -l $MOO_USER -c "echo $CURMD5HASH > ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.md5sum.old"
			su -l $MOO_USER -c "echo $MD5HASH > ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.md5sum"
			NEW=1
		fi

		OLDMD5HASH=$(cat ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.md5sum.old)

		echo "The old md5sum was $OLDMD5HASH the new md5sum is $MD5HASH"

		## replace old hash with new hash in info.php on local web server
		su -l $MOO_USER -c "sed -i \"s/$OLDMD5HASH/$MD5HASH/g\" /mnt/linux-pdq/media/truecrypt1/domains/pdqblog/info.php"

		## create initial old name
		if [ ! -f "${ABS_BASE_DIR}mooOS_${ARCH_ISO}.name.old" ]; then
			su -l $MOO_USER -c "echo mooOS-2013.09.02-beta-0.99-${ARCH_ISO}.iso > ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.name.old"
		fi

		cd $ISO_DIR
		## create initial current name
		if [ ! -f "${ABS_BASE_DIR}mooOS_${ARCH_ISO}.name" ]; then
			su -l $MOO_USER -c "ls *${ARCH_ISO}* > ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.name"
		fi

		NEW_NAME_LIST=$(ls *${ARCH_ISO}*)
		CURRELNAME=$(cat ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.name)
		OLDRELNAME=$(cat ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.name.old)

		cd "$PWD"
		NEW_NAME=0
		## if new iso create release name
		if [ "$CURRELNAME" != "$NEW_NAME_LIST" ]; then
			su -l $MOO_USER -c "echo $CURRELNAME > ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.name.old"
			su -l $MOO_USER -c "echo $NEW_NAME_LIST > ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.name"
			NEW_NAME=1
		fi

		CURRELNAME=$(cat ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.name)
		OLDRELNAME=$(cat ${ABS_BASE_DIR}mooOS_${ARCH_ISO}.name.old)

		echo "The old release name was $OLDRELNAME the new release name is $CURRELNAME"
		## replace old release name with new release name in info.php on local web server
		if [ $NEW_NAME -eq 1 ]; then
			su -l $MOO_USER -c "sed -i \"s/$OLDRELNAME/$CURRELNAME/g\" /mnt/linux-pdq/media/truecrypt1/domains/pdqblog/info.php"
		fi

		## Mount server filesystem to localhost
		# path to remote repo credentials file
		su -l $MOO_USER -c "cat /mnt/linux-pdq/media/truecrypt1/private/repo_creds > /tmp/repo_creds"
		REPO_CREDS=/tmp/repo_creds

		## if remote web server exists
		if [ "$REPO_CREDS" ] ; then
			. $REPO_CREDS

			dest=$(eval echo $(echo '${'_iso_sync[3]'}'))

			## copy info.php with new hash to remote web server
			echo "================syncing info.php to remote web server==================="
			su -l $MOO_USER -c "torsocks scp /mnt/linux-pdq/media/truecrypt1/domains/pdqblog/info.php $dest/public_html/"
			rm "$REPO_CREDS"
		fi

		notify-send "Release info done." -i "$MOO_ICON"
	fi

	question="${bldyellow}Do you wish to rysnc this ${ARCH_ISO} iso to local/remote servers (Y/N)?\n${txtrst}"
	if ask_something; then
		echo "
================syncing iso to local storage repos===================
"
		su -l $MOO_USER -c "rm $ISO_STORAGE/mooOS-beta-${ARCH_ISO}-old.iso"
		su -l $MOO_USER -c "mv -fv $ISO_STORAGE/mooOS-beta-${ARCH_ISO}.iso $ISO_STORAGE/mooOS-beta-${ARCH_ISO}-old.iso"
		su -l $MOO_USER -c "cp -fv $ISO_DIR/*-${ARCH_ISO}.iso $ISO_STORAGE/mooOS-beta-${ARCH_ISO}.iso"

		## Mount server filesystem to localhost
		# path to remote repo credentials file
		su -l $MOO_USER -c "cat /mnt/linux-pdq/media/truecrypt1/private/repo_creds > /tmp/repo_creds"
		REPO_CREDS=/tmp/repo_creds

		## if remote web server exists
		if [ "$REPO_CREDS" ] ; then
			. $REPO_CREDS

			## override credentials file
			_iso_sync[2]="$ISO_STORAGE/mooOS-beta-${ARCH_ISO}.iso"

			## rsync .iso using vars defined in credentials, e.g.:
			port=$(eval echo $(echo '${'_iso_sync[1]'}'))
			flags=$(eval echo $(echo '${'_iso_sync[4]'}'))
			src=$(eval echo $(echo '${'_iso_sync[2]'}'))
			dest=$(eval echo $(echo '${'_iso_sync[3]'}'))

			echo "================syncing iso to remote server==================="
			echo "This may take a while..."
			su -l $MOO_USER -c "rsync -avcPh $flags -e 'ssh -p $port' $src $dest" # -n, --dry-run perform a trial run with no changes made

			rm "$REPO_CREDS"
		fi
		
		echo "${ARCH_ISO} synced"
		notify-send "${ARCH_ISO} synced" -i "$MOO_ICON"
	fi
}

umount_work_env() {
	## unmount work env
	moo=$1
	question="${bldyellow}Do you wish to unmount the $moo work env (Y/N)?\n${txtrst}"
	if ask_something; then
		umount $WORK_DIR/$moo/root-image/dev
		umount $WORK_DIR/$moo/root-image/
		rm -r $WORK_DIR/$moo
		rm $WORK_DIR/*$moo

		rm -r $WORK_DIR/iso/$moo/$moo
		rm $WORK_DIR/iso/$moo/*.$moo.*

		rm -r $WORK_DIR/iso/$moo/boot/$moo
	fi
}

create_build_env() {
	question="${bldyellow}You wish to skip to create iso (Y/N)? (default: no)\n${txtrst}"
	if ! ask_something; then
		PWD=$(pwd)
		echo "${bldyellow}Copying configuration files and recreating repos now...${txtrst}"

		## copy root files

		## profile-sync-daemon
		cp -v /etc/psd.conf ${ARCHLIVE}archlive/releng/root-image/etc/psd.conf
		
		## resolv.conf
		cp -v /etc/resolv.conf ${ARCHLIVE}archlive/releng/root-image/etc/resolv.conf
		
		## resolv.conf.head
		cp -v /etc/resolv.conf.head ${ARCHLIVE}archlive/releng/root-image/etc/resolv.conf.head
		
		## dnsmasq
		cp -v /etc/dnsmasq.conf ${ARCHLIVE}archlive/releng/root-image/etc/dnsmasq.conf
		
		## dhcpcd
		cp -v /etc/dhcpcd.conf ${ARCHLIVE}archlive/releng/root-image/etc/dhcpcd.conf
		
		## nano config
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/usr/share/nano
		cp -v /usr/share/nano/pkgbuild.nanorc ${ARCHLIVE}archlive/releng/root-image//usr/share/nano/pkgbuild.nanorc
		
		## e17 backgrounds
		cp -v /usr/share/enlightenment/data/backgrounds/* ${ARCHLIVE}archlive/releng/root-image/usr/share/enlightenment/data/backgrounds
		
		## tor config
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/tor
		cp -v /etc/torrc ${ARCHLIVE}archlive/releng/root-image/etc/tor/torrc
		
		## privoxy config
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/privoxy
		sh -c "echo 'forward-socks5 / localhost:9050 .' > ${ARCHLIVE}archlive/releng/root-image/etc/privoxy/config"
		
		## dansguardian config
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/dansguardian
		cp -v /etc/dansguardian/dansguardian.conf ${ARCHLIVE}archlive/releng/root-image/etc/dansguardian/dansguardian.conf
		
		## squid config
		#mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/squid
		#cp -v /etc/squid/squid.conf ${ARCHLIVE}archlive/releng/root-image/etc/squid/squid.conf

		## TODO
		#mv -v /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.bak
		#cp -v ${dev_directory}etc/httpd.conf /etc/httpd/conf/httpd.conf
		#cp -v ${dev_directory}etc/httpd-phpmyadmin.conf /etc/httpd/conf/extra/httpd-phpmyadmin.conf
		#mv -v /etc/php/php.ini /etc/php/php.ini.bak
		#cp -v ${dev_directory}etc/php.ini /etc/php/php.ini

		## copy over custom .desktop files
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/usr/share/applications
		cp -v ${MOO_HOME}github/mooOS-dev-tools/applications/*.desktop ${ARCHLIVE}archlive/releng/root-image/usr/share/applications/
		
		## copy over ~/bin
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/bin
		cp -vr ${MOO_HOME}bin/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/bin
		
		## copy over pentadactyl files
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.pentadactyl/colors
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.pentadactyl/plugins
		cp -vr ${MOO_HOME}.pentadactyl/colors/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.pentadactyl/colors
		cp -vr ${MOO_HOME}.pentadactyl/plugins/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.pentadactyl/plugins
		
		## copy over rss reader files
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.canto-ng
		cp -v ${MOO_HOME}.canto-ng/config ${ARCHLIVE}archlive/releng/root-image/etc/skel/.canto-ng/config
		
		## copy over firefox files
		su -l $MOO_USER -c "cp -vr ${MOO_HOME}.mozilla/firefox/qrtww0pl.Default-User/* ${MOO_HOME}info/firefox/qrtww0pl.Default-User"
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.mozilla/firefox/qrtww0pl.Default-User
		cp -vr ${MOO_HOME}info/firefox/qrtww0pl.Default-User/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.mozilla/firefox/qrtww0pl.Default-User
		
		## copy over ~/.local files
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.local/applications
		cp -v ${MOO_HOME}.local/applications/defaults.list ${ARCHLIVE}archlive/releng/root-image/etc/skel/.local/applications/defaults.list
		cp -v ${MOO_HOME}.local/applications/tabbed.desktop ${ARCHLIVE}archlive/releng/root-image/etc/skel/.local/applications/tabbed.desktop
		cp -v ${MOO_HOME}.local/applications/URxvt.desktop ${ARCHLIVE}archlive/releng/root-image/etc/skel/.local/applications/URxvt.desktop
		cp -v ${MOO_HOME}.local/applications/install_mooOS.desktop ${ARCHLIVE}archlive/releng/root-image/etc/skel/.local/applications/install_mooOS.desktop
		cp -v ${MOO_HOME}.local/applications/man_mooOS.desktop ${ARCHLIVE}archlive/releng/root-image/etc/skel/.local/applications/man_mooOS.desktop
		
		## copy over ~/.* (dotfiles)
		cp -v ${MOO_HOME}.Xdefaults ${ARCHLIVE}archlive/releng/root-image/etc/skel/.Xdefaults
		cp -v ${MOO_HOME}.xinitrc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.xinitrc
		cp -v ${MOO_HOME}.zshrc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.zshrc
		cp -v ${MOO_HOME}.gtkrc-2.0 ${ARCHLIVE}archlive/releng/root-image/etc/skel/.gtkrc-2.0
		cp -v ${MOO_HOME}.nanorc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.nanorc
		cp -v ${MOO_HOME}.dialogrc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.dialogrc
		cp -v ${MOO_HOME}.pentadactylrc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.pentadactylrc			
		cp -v ${MOO_HOME}.dialogrc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.dialogrc
		cp -v ${MOO_HOME}.wgetrc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.wgetrc
		cp -v ${MOO_HOME}.curlrc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.curlrc
		
		## copy over ~/.themes
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.themes/Black
		cp -vr ${MOO_HOME}.themes/Black/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.themes/Black
		
		## copy over ~/.fonts
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.fonts
		cp -vr ${MOO_HOME}.fonts/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.fonts
		
		## copy over kde files
		mkdir -vp  ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/apps/color-schemes
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/apps/kdenlive
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/apps/dolphin/view_properties/global
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/config
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/kde4/services/ServiceMenus
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/apps/konsole
		cp -vr ${MOO_HOME}.kde4/share/apps/color-schemes/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/apps/color-schemes
		cp -v ${MOO_HOME}.kde4/share/apps/kdenlive/kdenliveui.rc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/apps/kdenlive/kdenliveui.rc
		cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/kdenliveuirc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/config/kdenliveuirc
		cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/..directory ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/apps/dolphin/view_properties/global/.directory
		cp -v ${MOO_HOME}.kde4/share/config/startupconfig ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/config/startupconfig
		cp -v ${MOO_HOME}.kde4/share/config/konsolerc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/config/konsolerc
		cp -v ${MOO_HOME}.kde4/share/config/kservicemenurc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/config/kservicemenurc 
		cp -vr ${MOO_HOME}.kde4/share/kde4/services/ServiceMenus/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/kde4/services/ServiceMenus
		cp -vr ${MOO_HOME}.kde4/share/apps/konsole/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/apps/konsole
		cp -v ${MOO_HOME}.kde4/share/config/dolphinrc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/config/dolphinrc
		cp -v ${MOO_HOME}.kde4/share/apps/dolphin/dolphinui.rc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/apps/dolphin/dolphinui.rc
		cp -v ${MOO_HOME}.kde4/share/config/gtkrc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/config/gtkrc
		cp -v ${MOO_HOME}.kde4/share/config/kcmdisplayrc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/config/kcmdisplayrc
		cp -v ${MOO_HOME}.kde4/share/config/gtkrc-2.0 ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/config/gtkrc-2.0
		
		## copy over ~/.gnupg
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.gnupg
		cp -v ${MOO_HOME}.gnupg/gpg-agent.conf ${ARCHLIVE}archlive/releng/root-image/etc/skel/.gnupg/gpg-agent.conf
		cp -v ${MOO_HOME}.gnupg/gpg.conf ${ARCHLIVE}archlive/releng/root-image/etc/skel/.gnupg/gpg.conf

		## copy over transmission file
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/transmission-daemon
		cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/settings.json ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/transmission-daemon/settings.json
		
		## copy over key-mon config
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/key-mon
		cp -v ${MOO_HOME}.config/key-mon/config ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/key-mon/config
		
		## copy lxtask config
		cp -v ${MOO_HOME}.config/lxtask.conf ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/lxtask.conf

		## copy Trolltech config
		cp -v ${MOO_HOME}.config/Trolltech.conf ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/Trolltech.conf
		
		## copy pavucontrol config
		cp -v ${MOO_HOME}.config/pavucontrol.ini ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/pavucontrol.ini
		
		## copy over mocp file
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.moc
		cp -v ${MOO_HOME}.moc/config ${ARCHLIVE}archlive/releng/root-image/etc/skel/.moc/config
		
		## copy htop file
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/htop
		cp -v ${MOO_HOME}.config/htop/htoprc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/htop/htoprc
		
		## copy sublime text 3 files
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/sublime-text-3/Packages/User
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/sublime-text-3/Packages/Theme\ -\ Nil
		cp -vr ${MOO_HOME}.config/sublime-text-3/Packages/Theme\ -\ Nil/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/sublime-text-3/Packages/Theme\ -\ Nil/
		cp -v ${MOO_HOME}.config/sublime-text-3/Packages/User/Preferences.sublime-settings ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
		
		## https://github.com/dmatarazzo/Sublime-Text-2-Icon
		echo "Updating Sublime Text 3 icons"
		# cp -v /usr/share/icons/HighContrast/16x16/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/HighContrast/16x16/apps/sublime-text.png
		# cp -v /usr/share/icons/HighContrast/256x256/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/HighContrast/256x256/apps/sublime-text.png
		# cp -v /usr/share/icons/HighContrast/32x32/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/HighContrast/32x32/apps/sublime-text.png
		# cp -v /usr/share/icons/HighContrast/48x48/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/HighContrast/48x48/apps/sublime-text.png
		# cp -v /usr/share/icons/gnome/16x16/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/gnome/16x16/apps/sublime-text.png
		# cp -v /usr/share/icons/gnome/256x256/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/gnome/256x256/apps/sublime-text.png
		# cp -v /usr/share/icons/gnome/32x32/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/gnome/32x32/apps/sublime-text.png
		# cp -v /usr/share/icons/gnome/48x48/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/gnome/48x48/apps/sublime-text.png
		# cp -v /usr/share/icons/hicolor/128x128/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/hicolor/128x128/apps/sublime-text.png
		# cp -v /usr/share/icons/hicolor/16x16/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/hicolor/16x16/apps/sublime-text.png
		# cp -v /usr/share/icons/hicolor/256x256/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/hicolor/256x256/apps/sublime-text.png
		# cp -v /usr/share/icons/hicolor/32x32/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/hicolor/32x32/apps/sublime-text.png
		# cp -v /usr/share/icons/hicolor/48x48/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/hicolor/48x48/apps/sublime-text.png
		# cp -v /usr/share/icons/oxygen/128x128/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/oxygen/128x128/apps/sublime-text.png
		# cp -v /usr/share/icons/oxygen/16x16/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/oxygen/16x16/apps/sublime-text.png
		# cp -v /usr/share/icons/oxygen/256x256/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/oxygen/256x256/apps/sublime-text.png
		# cp -v /usr/share/icons/oxygen/32x32/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/oxygen/32x32/apps/sublime-text.png
		# cp -v /usr/share/icons/oxygen/48x48/apps/sublime-text.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/oxygen/48x48/apps/sublime-text.png
		
		## mooOS icon
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-16.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/HighContrast/16x16/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-256.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/HighContrast/256x256/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-32.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/HighContrast/32x32/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-48.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/HighContrast/48x48/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-16.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/gnome/16x16/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-256.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/gnome/256x256/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-32.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/gnome/32x32/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-48.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/gnome/48x48/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-128.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/hicolor/128x128/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-16.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/hicolor/16x16/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-256.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/hicolor/256x256/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-32.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/hicolor/32x32/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-48.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/hicolor/48x48/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-128.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/oxygen/128x128/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-16.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/oxygen/16x16/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-256.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/oxygen/256x256/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-32.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/oxygen/32x32/apps/mooOS.png
		cp -v ${MOO_HOME}github/mooOS-dev-tools/images/mooOS-48.png ${ARCHLIVE}archlive/releng/root-image/usr/share/icons/oxygen/48x48/apps/mooOS.png
		
		## copy vlc files
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/vlc
		cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/vlc-qt-interface.conf ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/vlc/vlc-qt-interface.conf
		cp -v ${MOO_HOME}.config/vlc/vlcrc ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/vlc/vlcrc
		
		## copy over window manager files
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/applications
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/backgrounds
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/config
		rm -r ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/themes
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/images
		cp -vr ${MOO_HOME}.e/e/applications/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/applications
		#cp -vr ${MOO_HOME}.e/e/backgrounds/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/backgrounds
		cp -vr ${MOO_HOME}.e/e/config/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/config
		#cp -vr ${MOO_HOME}.e/e/themes/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/themes
		#cp -v ${MOO_HOME}.e/e/images/tw_cache_images.eet ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/images/tw_cache_images.eet
		rm ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/config/standard/module.everything.cache.*
		rm ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/config/standard/exehist.*
		rm ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/config/standard/evry_exebuf_cache.*
		rm ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/config/standard/module.forecasts.*
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/usr/share/enlightenment/data/themes
		cp -vr /usr/share/enlightenment/data/themes/* ${ARCHLIVE}archlive/releng/root-image/usr/share/enlightenment/data/themes

		## patch config files for username
		cd ${ARCHLIVE}archlive/releng/root-image/etc/skel/.e/e/config/standard
		for NEW_FILE in e.*
		do
			EWW_FILE=${NEW_FILE/.cfg/.src}
			eet -d $NEW_FILE config $EWW_FILE
			sed -i "s/$MOO_USER/moo/g" $EWW_FILE
			rm $NEW_FILE
			eet -e $NEW_FILE config $EWW_FILE 1
			rm $EWW_FILE
		done
		cd "$PWD"
	
		## terminology
		cp -vr ${MOO_HOME}.config/terminology/config/standard/base.cfg ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/terminology/config/standard/base.cfg
		## patch config files for username
		cd  ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/terminology/config/standard/
		eet -d base.cfg config base.src
		sed -i "s/$MOO_USER/moo/g" base.src
		rm base.cfg
		eet -e base.cfg config base.src 1
		rm base.src
		cd "$PWD"

		## clean up files content
		sed -i "s/$MOO_USER/moo/g" ${ARCHLIVE}archlive/releng/root-image/etc/skel/.mozilla/firefox/qrtww0pl.Default-User/extensions.ini
		sed -i "s/$MOO_USER/moo/g" ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/transmission-daemon/settings.json
		sed -i "s/$MOO_USER/moo/g" ${ARCHLIVE}archlive/releng/root-image/etc/skel/.moc/config
		sed -i "s/$MOO_USER/moo/g" ${ARCHLIVE}archlive/releng/root-image/etc/skel/.kde4/share/config/dolphinrc
		sed -i "s/$MOO_USER/moo/g" ${ARCHLIVE}archlive/releng/root-image/etc/psd.conf 
		sed -i "s/$MOO_USER/moo/g" ${ARCHLIVE}archlive/releng/root-image/etc/skel/.gtkrc-2.0		

		## copy over hosts file (needed for LAN repos) TODO
		#cp -v /etc/hosts ${ARCHLIVE}archlive/releng/root-image/etc/hosts

		## cleanup Github local repos
		rm -rf ${ARCHLIVE}archlive/releng/root-image/etc/skel/Github
		## mooOS stuffs
	 	mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/Desktop
	 	mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/Dev/mooOS_backups
	 	mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/Downloads
	 	mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/Videos
	 	mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/Dropbox
	 	mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/Github
	 	mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/Music
	 	mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/Pictures
	 	cp -vr ${MOO_HOME}info/mooOS_backups/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/Dev/mooOS_backups

	 	## copy home files and create default directories
	 	cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/Desktop.* ${ARCHLIVE}archlive/releng/root-image/etc/skel/Desktop/
	 	cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/Dev.* ${ARCHLIVE}archlive/releng/root-image/etc/skel/Dev/
	 	cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/Downloads.* ${ARCHLIVE}archlive/releng/root-image/etc/skel/Downloads/
	 	cp -v ${MOO_HOME}Videos/Videos.* ${ARCHLIVE}archlive/releng/root-image/etc/skel/Videos/
	 	#cp -v ${MOO_HOME}Dropbox/Dropbox.* ${ARCHLIVE}archlive/releng/root-image/etc/skel/Dropbox/
	 	cp -v ${MOO_HOME}github/Github.* ${ARCHLIVE}archlive/releng/root-image/etc/skel/Github/
	 	cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/Music.* ${ARCHLIVE}archlive/releng/root-image/etc/skel/Music/
	 	cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/Pictures.* ${ARCHLIVE}archlive/releng/root-image/etc/skel/Pictures/

		## create ~/Github and all repos
		cd ${ARCHLIVE}archlive/releng/root-image/etc/skel/Github
		git clone git://github.com/idk/pdq.git
		git clone git://github.com/idk/bin.git
		#git clone git://github.com/idk/awesomewm-X.git
		git clone git://github.com/idk/zsh.git
		git clone git://github.com/idk/bin.git
		git clone git://github.com/idk/php.git
		git clone git://github.com/idk/systemd.git
		git clone git://github.com/idk/eggdrop-scripts.git
		git clone git://github.com/idk/gh.git
		git clone git://github.com/idk/vb-pdq.git
		git clone git://github.com/idk/mooOS-dev-tools.git
		git clone git://github.com/idk/mooOS-wallpapers.git
		cd "$PWD"

		## vimb files copied
		cp -v ${ARCHLIVE}archlive/releng/root-image/etc/skel/Github/vb-pdq/config ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/vimb/
		cp -v ${ARCHLIVE}archlive/releng/root-image/etc/skel/Github/vb-pdq/config_proxy ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/vimb/
		cp -v ${ARCHLIVE}archlive/releng/root-image/etc/skel/Github/vb-pdq/style.css ${ARCHLIVE}archlive/releng/root-image/etc/skel/.config/vimb/

		## preserve wallpapers
		mkdir -vp ${ARCHLIVE}archlive/releng/root-image/etc/skel/Github/sources/backgrounds
		cp -vr /usr/share/backgrounds/* ${ARCHLIVE}archlive/releng/root-image/etc/skel/Github/sources/backgrounds

		install -Dm644 "${ARCHLIVE}archlive/releng/root-image/etc/skel/Github/mooOS-dev-tools/misc/man.1" "${ARCHLIVE}archlive/releng/root-image/usr/local/man/man1/mooOS.1"
		gzip -f ${ARCHLIVE}archlive/releng/root-image/usr/local/man/man1/mooOS.1

		echo "${bldyellow}Removing previous build and work directories...${txtrst}"
		
		## deprecated method
		if [ -d "${ARCHLIVE}archlive/releng/work" ]; then
			rm -r ${ARCHLIVE}archlive/releng/work
		fi

		## new method
		if [ -d "$ISO_DIR" ]; then
			rm -r "$ISO_DIR"
		fi
		if [ -d "$WORK_DIR" ]; then
			rm -r "$WORK_DIR"
		fi

		## create pacman.conf for build
		mkdir -v "$WORK_DIR" && cp ${MOO_HOME}github/mooOS-dev-tools/misc/pacman.conf ${WORK_DIR}/pacman.conf

		mkdir -v "${ARCHLIVE}archlive/releng/work"
		
		## create pacman.conf for livecd
		cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/pacman.conf ${ARCHLIVE}archlive/releng/work/pacman.conf
		
		## create pacman.conf for livecd specific to architecture
		cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/pacman-x86_64.conf ${ARCHLIVE}archlive/releng/root-image/etc/pacman-x86_64.conf
		cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/pacman-i686.conf ${ARCHLIVE}archlive/releng/root-image/etc/pacman-i686.conf
		cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/pacman-x86_64.conf ${ARCHLIVE}archlive/releng/work/pacman-x86_64.conf
		cp -v ${MOO_HOME}github/mooOS-dev-tools/misc/pacman-i686.conf ${ARCHLIVE}archlive/releng/work/pacman-i686.conf

		## packages lists
		#cp -v ${MOO_HOME}github/mooOS-dev-tools/packages.both ${ARCHLIVE}archlive/releng/packages.both
		#pacman -Qqe  | grep -vx "$(pacman -Qqg base)" | grep -vx "$(cat ${MOO_HOME}github/mooOS-dev-tools/backup_exclude_pkgs)" > ${ARCHLIVE}archlive/releng/packages.both

		cp -v ${MOO_HOME}github/mooOS-dev-tools/packages.extra ${ARCHLIVE}archlive/releng/packages.extra
		cp -v ${MOO_HOME}github/mooOS-dev-tools/packages-server.both ${ARCHLIVE}archlive/releng/packages-server.both
		cp -v ${MOO_HOME}github/mooOS-dev-tools/packages.i686 ${ARCHLIVE}archlive/releng/packages.i686
		cp -v ${MOO_HOME}github/mooOS-dev-tools/packages.x86_64 ${ARCHLIVE}archlive/releng/packages.x86_64

		## copy over boot splash screen and mooOS branding
		cp -v ${ARCHLIVE}archlive/releng/syslinux/splash.png ${ARCHLIVE}archlive/releng/root-image/etc/grub.d/splash.png
		convert ${ARCHLIVE}archlive/releng/root-image/etc/grub.d/splash.png ${ARCHLIVE}archlive/releng/root-image/etc/grub.d/splash.jpg
		#cp -v /etc/arch-release ${ARCHLIVE}archlive/releng/root-image/etc/arch-release
	fi
		notify-send "Files copied!" -i "$MOO_ICON"

}

create_mooos_repos() {
	question="${bldyellow}Create and cleanup mooOS repos? (Y/N)?\n${txtrst}"
	if ask_something; then
		echo "${bldgreen}Recreating repos now...${txtrst}"
		## remove existing repos
		rm -v ${ABS_BASE_DIR}mooOS-pkgs-32/mooOS.db.tar.gz
		rm -v ${ABS_BASE_DIR}mooOS-pkgs-64/mooOS.db.tar.gz
		#rm ${ABS_BASE_DIR}mooOS-utils/mooOS-utils.db.tar.gz

		## hackity hack hack - clean up old git package caches
		arches="32 64"
		for mm in $arches
		do
			cd ${MOO_HOME}abs/mooOS-pkgs-$mm/
			mv -v $(ls | grep "efl-git-1" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "efl-git-debug-1" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "elementary-git-1" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "elementary-git-debug-1" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "elementary_test-git-1" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "elementary_test-git-debug-1" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "enlightenment17-git-0" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "enlightenment17-git-debug" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "evas_generic_loaders-git-1" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "evas_generic_loaders-git-debug-1" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "pulseaudio-mixer-cli-git" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "pyradio-git" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "sqlmap-git" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "terminology-git-0" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "terminology-git-debug-0" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "urxvt-font-size-git" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			mv -v $(ls | grep "youtube-viewer-git" | sort -r | head -2) ${MOO_HOME}abs/staging_$mm/
			rm -v ${MOO_HOME}abs/mooOS-pkgs-$mm/*-git*
			mv -v ${MOO_HOME}abs/staging_$mm/* ${MOO_HOME}abs/mooOS-pkgs-$mm/
			cd "$PWD"
		done

		rm -vf ${MOO_HOME}abs/i686/*-git*
		rm -vf ${MOO_HOME}abs/x86_64/*-git*

		## make RMS happy :D
		rm -vf ${ABS_BASE_DIR}mooOS-pkgs-*/*-libre-*
		cp -v ${MOO_HOME}abs/i686/*-libre-*-i686* ${ABS_BASE_DIR}mooOS-pkgs-32/
		cp -v ${MOO_HOME}abs/x86_64/*-libre-*-x86_64* ${ABS_BASE_DIR}mooOS-pkgs-64/

		rm -vf ${ABS_BASE_DIR}mooOS-pkgs-*/*-libre-*any*
		cp -v ${MOO_HOME}abs/i686/*-libre-*-any* ${ABS_BASE_DIR}mooOS-pkgs-32/
		cp -v ${MOO_HOME}abs/x86_64/*-libre-*-any* ${ABS_BASE_DIR}mooOS-pkgs-64/

		rm -vf ${ABS_BASE_DIR}mooOS-pkgs-*/unar-*
		cp -v ${MOO_HOME}abs/i686/unar-*-i686* ${ABS_BASE_DIR}mooOS-pkgs-32/
		cp -v ${MOO_HOME}abs/x86_64/unar-*-x86_64* ${ABS_BASE_DIR}mooOS-pkgs-64/

		rm -vf ${ABS_BASE_DIR}mooOS-pkgs-*/opencollada-*
		cp -v ${MOO_HOME}abs/i686/opencollada-*-i686* ${ABS_BASE_DIR}mooOS-pkgs-32/
		cp -v ${MOO_HOME}abs/x86_64/opencollada-*-x86_64* ${ABS_BASE_DIR}mooOS-pkgs-64/

		rm -vf ${ABS_BASE_DIR}mooOS-pkgs-*/mozilla-searchplugins-*
		cp -v ${MOO_HOME}abs/i686/mozilla-searchplugins-*-any* ${ABS_BASE_DIR}mooOS-pkgs-32/
		cp -v ${MOO_HOME}abs/x86_64/mozilla-searchplugins-*-any* ${ABS_BASE_DIR}mooOS-pkgs-64/

		## create repo databases
		echo "${bldmagenta}Re-creating i686 repository${txtrst}"
		repo-add -k $GPGKEY ${ABS_BASE_DIR}mooOS-pkgs-32/mooOS.db.tar.gz ${ABS_BASE_DIR}mooOS-pkgs-32/*.pkg.tar.xz
		echo "${bldmagenta}Re-creating x86_64 repository${txtrst}"
		repo-add -k $GPGKEY ${ABS_BASE_DIR}mooOS-pkgs-64/mooOS.db.tar.gz ${ABS_BASE_DIR}mooOS-pkgs-64/*.pkg.tar.xz
		#echo "${bldyellow}Re-creating utils repository${txtrst}"
		#repo-add ${ABS_BASE_DIR}mooOS-utils/mooOS-utils.db.tar.gz ${ABS_BASE_DIR}mooOS-pkgs-64/*.pkg.tar.xz >> $REPO_LOG_TEMP 2>&1

		## format log a little
		echo $(date -d "today" +"%Y%m%d%H%M") >> $REPO_LOG_TEMP
		sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" $REPO_LOG_TEMP >> $MOO_LOG

		notify-send "Repos created!" -i "$MOO_ICON"

		## clean up stable repos
		## re-create repos local and remoteed 
		echo "================syncing to local repos==================="
		rsync -avzrcpPh --delete --stats ${REPO_BASE_DIR}/i686/ ${ABS_BASE_DIR}mooOS-pkgs-32-out-of-date
		rsync -avzrcpPh --delete --stats ${REPO_BASE_DIR}/x86_64/ ${ABS_BASE_DIR}mooOS-pkgs-64-out-of-date
		rsync -avzrcpPh --delete --stats ${ABS_BASE_DIR}mooOS-pkgs-32/ ${REPO_BASE_DIR}/i686
		rsync -avzrcpPh --delete --stats ${ABS_BASE_DIR}mooOS-pkgs-64/ ${REPO_BASE_DIR}/x86_64
		notify-send "Repos synced to local server!" -i "$MOO_ICON"

	fi
}

sync_mooos_repos() {
	question="${bldyellow}Sync remote mooOS repo? (Y/N)?\n${txtrst}"
	if ask_something; then
		## include login credentials:
		if [ -f "$REPO_CREDS" ] ; then
			echo "================syncing to remote repos==================="
			. $REPO_CREDS

			## rsync using vars defined in credentials, e.g.:
			#for i in {1..5}
			for i in $(eval echo {1..$_remote_count})
			do
				port=$(eval echo $(echo '${'_remote$i[1]'}'))
				flags=$(eval echo $(echo '${'_remote$i[4]'}'))
				src=$(eval echo $(echo '${'_remote$i[2]'}'))
				dest=$(eval echo $(echo '${'_remote$i[3]'}'))
				torsocks rsync -avzrcPh $flags -e "torsocks ssh -p $port" $src $dest # -n, --dry-run perform a trial run with no changes made
			done
			notify-send "Repos synced to remote server!" -i "$MOO_ICON"
		fi
	fi
}

# github_sync() {
# 	question="${bldyellow}Sync to github? (Y/N)?\n${txtrst}"
# 	if ask_something; then
# 		gh -b ## https://github.com/idk/gh
# 	fi
# }
