#!/usr/bin/bash
## chroot-install.sh sub-script for chroot fo mooOS =)
## 2013-2014 pdq
## for mooOS

boot_part=$1

upper_title="[ mooOS environment configuration ] (chroot)"

if [ ! -f /usr/bin/dialog ] || [ ! -f /usr/bin/eet ]; then
    echo "Missing expected installed packages...returning to Installer, (Re-installation  needed)."
    sleep 10s
    exit 0
    exit 0 
fi

# dialog --clear --backtitle "$upper_title" --title "Preferences" --yes-label "Text Mode" --no-label "Graphical Mode" --yesno "Chose the Installer Type." 20 70
# if [ $? = 0 ] ; then
      DIALOG=${DIALOG=dialog}
# else
#     DIALOG=${DIALOG=Xdialog}
# fi

## only allow root to run script
if [ $(id -u) -eq 0 ]; then

    ## TODO sanity checks

    ## styling
    ## styling
    clr="\Zb"
    clr_end="\Zn"

    ## temporary files
    _TEMP=/tmp/chanswer$$
    mkdir -p /tmp/tmp 2>/dev/null
    TMP=/tmp/tmp 2>/dev/null
    echo "unset" > $TMP/rootpasswd

    _CURRENT=/tmp/current
    echo "8" > $_CURRENT

    _CCURRENT=/tmp/ccurrent
    echo "1" > $_CCURRENT

    #setterm -blank 0

    ## functions

    exiting() {
        clear
        rm -f $_TEMP
        $DIALOG --clear --backtitle "$upper_title" --title "[ Return to Installer ]" --msgbox "Proceed." 10 30
        exit 0
        exit 0
    }

    current_selection() {
        echo "$1" > $_CCURRENT
    }

    gen_tz() {
        $DIALOG --clear --backtitle "$upper_title" --title "[ TIMEZONE ]" --msgbox "Generate timezone/localtime  [ ESC to return to menu ]" 10 40
        if [ $? = 255 ] ; then
            chroot_menu
            return 0
        fi

        local tz_list tz
        for tz in $(grep -v "#" /usr/share/zoneinfo/zone.tab | awk '{print $3}' | sort) ; do
            tz_list+="${tz} - "
        done

        GEN_TIMEZONE=$($DIALOG --stdout --backtitle "${upper_title}" --title '[ TIMEZONE ]' --cancel-label "Go Back" \
           --default-item "${GEN_TIMEZONE}" --menu "Choose timezone or <Go Back> to return" 16 40 23 ${tz_list} "null" "-" || echo "${GEN_TIMEZONE}")

        if [ "$GEN_TIMEZONE" = "" ] ; then
            chroot_menu
            return 0
        fi

        if [ -f "/usr/share/zoneinfo/$GEN_TIMEZONE" ] ; then
            ln -s /usr/share/zoneinfo/$GEN_TIMEZONE /etc/localtime
            $DIALOG --clear --backtitle "$upper_title" --title "[ TIMEZONE ]" --msgbox "Set timezone to $GEN_TIMEZONE" 10 30
        else
            $DIALOG --clear --backtitle "$upper_title" --title "[ TIMEZONE ]" --msgbox "Failed to set timezone...timezone does not exist?" 10 30
        fi
        current_selection 3
    }

    gen_hostname() {
        $DIALOG --clear --backtitle "$upper_title" --title "[ HOSTNAME ]" --msgbox "Generate hostname  [ ESC to return to menu ]" 10 30
        if [ $? = 255 ] ; then
            chroot_menu
            return 0
        fi

        GEN_HOSTNAME=$($DIALOG --stdout --backtitle "${upper_title}" --title '[ HOSTNAME ]' --cancel-label "Go Back" \
           --inputbox "Enter desired hostname or <Go Back> to return" 9 40 "${GEN_HOSTNAME}" || echo "${GEN_HOSTNAME}")
      
        if [ "$GEN_HOSTNAME" = "" ] ; then
            chroot_menu
            return 0
        fi

        echo $GEN_HOSTNAME > /etc/hostname
        $DIALOG --clear --backtitle "$upper_title" --title "[ HOSTNAME ]" --msgbox "Set hostname to $GEN_HOSTNAME" 10 30
        current_selection 2
    }

    gen_locale() {
        $DIALOG --clear --backtitle "$upper_title" --title "[ LOCALES ]" --msgbox "Generate locale [ ESC to return to menu ]" 10 30
        
        if [ $? = 255 ] ; then
            chroot_menu
            return 0
        fi

        GEN_LANG=$($DIALOG --stdout --backtitle "${upper_title}" --title '[ LOCALES ]' --cancel-label "Go Back" --default-item "${GEN_LANG}" \
           --menu "Choose a locale or <Go Back> to return" 16 40 23 \
            en_US.UTF-8 - \
            en_AU.UTF-8 - \
            en_BW.UTF-8 - \
            en_CA.UTF-8 - \
            en_DK.UTF-8 - \
            en_GB.UTF-8 - \
            en_HK.UTF-8 - \
            en_IE.UTF-8 - \
            en_NZ.UTF-8 - \
            en_PH.UTF-8 - \
            en_SG.UTF-8 - \
            en_US.UTF-8 - \
            en_ZA.UTF-8 - \
            en_ZW.UTF-8 - \
            aa_DJ.UTF-8 - \
            af_ZA.UTF-8 - \
            an_ES.UTF-8 - \
            ar_AE.UTF-8 - \
            ar_BH.UTF-8 - \
            ar_DZ.UTF-8 - \
            ar_EG.UTF-8 - \
            ar_IQ.UTF-8 - \
            ar_JO.UTF-8 - \
            ar_KW.UTF-8 - \
            ar_LB.UTF-8 - \
            ar_LY.UTF-8 - \
            ar_MA.UTF-8 - \
            ar_OM.UTF-8 - \
            ar_QA.UTF-8 - \
            ar_SA.UTF-8 - \
            ar_SD.UTF-8 - \
            ar_SY.UTF-8 - \
            ar_TN.UTF-8 - \
            ar_YE.UTF-8 - \
            ast_ES.UTF-8 - \
            be_BY.UTF-8 - \
            bg_BG.UTF-8 - \
            br_FR.UTF-8 - \
            bs_BA.UTF-8 - \
            ca_AD.UTF-8 - \
            ca_ES.UTF-8 - \
            ca_FR.UTF-8 - \
            ca_IT.UTF-8 - \
            cs_CZ.UTF-8 - \
            cy_GB.UTF-8 - \
            da_DK.UTF-8 - \
            de_AT.UTF-8 - \
            de_BE.UTF-8 - \
            de_CH.UTF-8 - \
            de_DE.UTF-8 - \
            de_LU.UTF-8 - \
            el_CY.UTF-8 - \
            el_GR.UTF-8 - \
            es_AR.UTF-8 - \
            es_BO.UTF-8 - \
            es_CL.UTF-8 - \
            es_CO.UTF-8 - \
            es_CR.UTF-8 - \
            es_DO.UTF-8 - \
            es_EC.UTF-8 - \
            es_ES.UTF-8 - \
            es_GT.UTF-8 - \
            es_HN.UTF-8 - \
            es_MX.UTF-8 - \
            es_NI.UTF-8 - \
            es_PA.UTF-8 - \
            es_PE.UTF-8 - \
            es_PR.UTF-8 - \
            es_PY.UTF-8 - \
            es_SV.UTF-8 - \
            es_US.UTF-8 - \
            es_UY.UTF-8 - \
            es_VE.UTF-8 - \
            et_EE.ISO-8859-15 - \
            et_EE.UTF-8 - \
            eu_ES.UTF-8 - \
            fi_FI.UTF-8 - \
            fo_FO.UTF-8 - \
            fr_BE.UTF-8 - \
            fr_CA.UTF-8 - \
            fr_CH.UTF-8 - \
            fr_FR.UTF-8 - \
            fr_LU.UTF-8 - \
            ga_IE.UTF-8 - \
            gd_GB.UTF-8 - \
            gl_ES.UTF-8 - \
            gv_GB.UTF-8 - \
            he_IL.UTF-8 - \
            hr_HR.UTF-8 - \
            hsb_DE.UTF-8 - \
            hu_HU.UTF-8 - \
            hy_AM.ARMSCII-8 - \
            id_ID.UTF-8 - \
            is_IS.UTF-8 - \
            it_CH.UTF-8 - \
            it_IT.UTF-8 - \
            iw_IL.UTF-8 - \
            ja_JP.EUC-JP - \
            ja_JP.UTF-8 - \
            ka_GE.UTF-8 - \
            kk_KZ.UTF-8 - \
            kl_GL.UTF-8 - \
            ko_KR.EUC-KR - \
            ko_KR.UTF-8 - \
            ku_TR.UTF-8 - \
            kw_GB.UTF-8 - \
            lg_UG.UTF-8 - \
            lt_LT.UTF-8 - \
            lv_LV.UTF-8 - \
            mg_MG.UTF-8 - \
            mi_NZ.UTF-8 - \
            mk_MK.UTF-8 - \
            ms_MY.UTF-8 - \
            mt_MT.UTF-8 - \
            nb_NO.UTF-8 - \
            nl_BE.UTF-8 - \
            nl_NL.UTF-8 - \
            nn_NO.UTF-8 - \
            oc_FR.UTF-8 - \
            om_KE.UTF-8 - \
            pl_PL.UTF-8 - \
            pt_BR.UTF-8 - \
            pt_PT.UTF-8 - \
            ro_RO.UTF-8 - \
            ru_RU.KOI8-R - \
            ru_RU.UTF-8 - \
            ru_UA.UTF-8 - \
            sk_SK.UTF-8 - \
            sl_SI.UTF-8 - \
            so_DJ.UTF-8 - \
            so_KE.UTF-8 - \
            so_SO.UTF-8 - \
            sq_AL.UTF-8 - \
            st_ZA.UTF-8 - \
            sv_FI.UTF-8 - \
            sv_SE.UTF-8 - \
            tg_TJ.UTF-8 - \
            th_TH.UTF-8 - \
            tl_PH.UTF-8 - \
            tr_CY.UTF-8 - \
            tr_TR.UTF-8 - \
            uk_UA.UTF-8 - \
            vi_VN.TCVN - \
            wa_BE.UTF-8 - \
            xh_ZA.UTF-8 - \
            yi_US.UTF-8 - \
            zh_CN.GB18030 - \
            zh_CN.GBK - \
            zh_CN.UTF-8 - \
            zh_HK.UTF-8 - \
            zh_SG.GBK - \
            zh_SG.UTF-8 - \
            zh_TW.EUC-TW - \
            zh_TW.UTF-8 - \
            zu_ZA.UTF-8 - "null" "-" || echo "${GEN_LANG}")
    
        if [ "$GEN_LANG" = "" ] ; then
            chroot_menu
            return 0
        fi

        echo "${GEN_LANG} ${GEN_LANG##*.}" > "/etc/locale.gen"
        echo "LANG=${GEN_LANG}" > "/etc/locale.conf"
        export "LANG=${GEN_LANG}"
        locale-gen 1>/dev/null || echo "Unable to setup the locales to" "${GEN_LANG}"
        $DIALOG --clear --backtitle "$upper_title" --title "[ LOCALES ]" --msgbox "Set locale to ${GEN_LANG}" 10 30
        current_selection 4
    }

    set_root_pass() {
        $DIALOG --clear --backtitle "$upper_title" --title "[ ROOT PASSWD ]" --msgbox "Set root password [ ESC to return to menu ]" 10 30
        
        if [ $? = 255 ] ; then
            chroot_menu
            return 0
        fi

        passwd
        echo "set" > $TMP/rootpasswd
        usermod -s /usr/bin/zsh root
        $DIALOG --clear --backtitle "$upper_title" --title "[ ROOT PASSWD ]" --msgbox "root password set!" 10 30
        current_selection 5
    }

    add_user() {
        $DIALOG --clear --backtitle "$upper_title" --title "[ CREATE USER ]" --msgbox "Create user and/or add password/sudoers [ ESC to return to menu ]" 10 30
        if [ $? = 255 ] ; then
            chroot_menu
            return 0
        fi

        $DIALOG --clear --backtitle "$upper_title" --title "[ CREATE USER ]" --yesno "Create default user? [mandatory]" 10 30
        if [ $? = 0 ] ; then
            $DIALOG --clear --backtitle "$upper_title" --title "[ CREATE USER ]" --inputbox "Please choose your username:\n\n" 10 70 2> $TMP/puser
            puser=$(cat $TMP/puser)
            #if [ "$puser" != "" ]; then
                useradd -m -g users -s /usr/bin/zsh $puser
            #fi
        #fi

        puser=$(cat $TMP/puser)

        #if [ "$puser" != "" ]; then
            $DIALOG --clear --backtitle "$upper_title" --title "[ CREATE USER ]" --msgbox "Next step is to add password for $puser [ ESC to return to menu ]" 10 30
            if [ $? = 255 ] ; then
                chroot_menu
                return 0
            fi

            $DIALOG --clear --backtitle "$upper_title" --title "[ CREATE USER ]" --yesno "Create/Edit password for $puser? [suggested: Yes]" 10 30
            if [ $? = 0 ] ; then
                passwd $puser
            fi

            $DIALOG --clear --backtitle "$upper_title" --title "[ CREATE USER ]" --yesno "Require no password for sudo? [suggested: Yes]" 10 30
            if [ $? = 0 ] ; then
                cp /etc/sudoers /etc/sudoers.bak
                sh -c "echo '$puser ALL=(ALL) NOPASSWD: ALL' >>  /etc/sudoers"
                npasswd="no password required"
            else
                cp /etc/sudoers /etc/sudoers.bak
                sh -c "echo '$puser ALL=(ALL) ALL' >>  /etc/sudoers"
                npasswd="password required"
            fi

            sh -c "echo 'Defaults timestamp_timeout=-1,insults,!env_editor,editor=\"/usr/bin/nano:/usr/bin/vim:/usr/bin/vi\"
Defaults !tty_tickets' >>  /etc/sudoers"

            $DIALOG --clear --backtitle "$upper_title" --title "[ CREATE USER ]" --defaultno --yesno "Confirm/view sudoers?" 10 30
            if [ $? = 0 ] ; then
                EDITOR=nano visudo
            fi

            ## patch config files for username
            PWD=$(pwd)
            cd /etc/skel/.e/e/config/standard
            for NEW_FILE in e.*
            do
                EWW_FILE=${NEW_FILE/.cfg/.src}

                eet -d $NEW_FILE config $EWW_FILE
                sed -i "s/moo/$puser/g" $EWW_FILE
                rm $NEW_FILE
                eet -e $NEW_FILE config $EWW_FILE 1
                rm $EWW_FILE
            done
            cd $PWD

            ## clean up files content
            sed -i "s/moo/$puser/g" /etc/skel/.mozilla/firefox/qrtww0pl.Default-User/extensions.ini
            sed -i "s/moo/$puser/g" /etc/skel/.config/transmission-daemon/settings.json
            sed -i "s/moo/$puser/g" /etc/skel/.moc/config
            sed -i "s/moo/$puser/g" /etc/skel/.kde4/share/config/dolphinrc
            sed -i "s/moo/$puser/g" /etc/psd.conf
            sed -i "s/moo/$puser/g" /etc/skel/.gtkrc-2.0

            ## add moo keys
            #pacman-key -r E73F68F6 --keyserver hkp://subkeys.pgp.net
            #pacman-key --lsign-key E73F68F6

            update-mirrorlist
            pacman -Syyu --noconfirm

            $DIALOG --clear --backtitle "$upper_title" --title "[ CREATE USER ]" --msgbox "Added the user $puser with $npsswd for sudo." 10 30
        fi

        current_selection 6
    }

    install_bootloader() {
        $DIALOG --clear --backtitle "$upper_title" --title "[ BOOTLOADER ]" --msgbox "Install Bootloader [ ESC to return to menu ]" 10 30
        if [ $? = 255 ] ; then
            chroot_menu
            return 0
        fi
        
        $DIALOG --clear --backtitle "$upper_title" --title "[ BOOTLOADER ]" --radiolist "Select bootloader" 20 70 30 \
        "1" "syslinux" on \
        "2" "grub" off \
        2> $TMP/pbootloader
        if [ $? = 1 ] || [ $? = 255 ] ; then
            chroot_menu
            return 0
        fi

        pbootloader=$(cat $TMP/pbootloader)
        if [ "$pbootloader" == "2" ] ; then
            $DIALOG --clear --backtitle "$upper_title" --title "[ GRUB 2]" --radiolist "Select grub type" 20 70 30 \
            "1" "grub-bios" on \
            "2" "grub-efi" off \
            2> $TMP/pgrub
            if [ $? = 1 ] || [ $? = 255 ] ; then
                chroot_menu
                return 0
            fi

            pgrub=$(cat $TMP/pgrub)
            if [ "$pgrub" == "1" ] ; then
                pacman -S --noconfirm --needed grub-bios
            else
                pacman -S --noconfirm --needed grub-efi-x86_64
            fi

            # choose boot/root drive
            $DIALOG --clear --backtitle "$upper_title" --title "[ GRUB 2 ]" --inputbox "Please choose the disk to install grub to.\n\n This should be the same drive your boot or root partition is on:\n\nUsually /dev/sda. Be careful!" 10 70 2> $TMP/bout
            if [ $? = 1 ] || [ $? = 255 ] ; then
                chroot_menu
                return 0
            fi

            bout=$(cat $TMP/bout)
            bootmsg="grub-install --target=i386-pc --recheck $bout"
           
            $DIALOG --clear --backtitle "$upper_title" --title "[ GRUB 2 ]" --yesno "Is this correct?\n\n grub-install --target=i386-pc --recheck $bout" 10 30
            if [ $? = 0 ] ; then
                grub-install --target=i386-pc --recheck $bout
                $DIALOG --clear --backtitle "$upper_title" --title "[ GRUB 2 ]" --msgbox "Grub installed" 10 30
    
                $DIALOG --clear --backtitle "$upper_title" --title "[ GRUB CONFIGURE ]" --msgbox "Configure Grub" 10 30
                if [ $? = 1 ] ; then
                    chroot_menu
                    return 0
                fi

                ## TODO
                cp -v /usr/share/locale/en\@quot/LC_MESSAGES/grub.mo /boot/grub/locale/en.mo
                grub-mkconfig -o /boot/grub/grub.cfg
                $DIALOG --clear --backtitle "$upper_title" --title "[ GRUB CONFIGURE ]" --msgbox "Grub configured" 10 30

            else
                $DIALOG --clear --backtitle "$upper_title" --title "[ GRUB 2 ]" --msgbox "Grub not installed..." 10 30
            fi
        else
            pacman -S --noconfirm --needed syslinux
            syslinux-install_update -i -a -m
            $DIALOG --clear --backtitle "$upper_title" --title "[ SYSLINUX ]" --msgbox "Syslinux installed" 10 30
            if [ "$boot_part" != ""]; then
                $DIALOG --clear --backtitle "$upper_title" --title "[ SYSLINUX ]" --yesno "Is $boot_part your boot drive?" 10 30
            else
                # choose boot/root drive
                $DIALOG --clear --backtitle "$upper_title" --title "[ SYSLINUX ]" --inputbox "Please choose the disk to install syslinux to.\n\n This should be the same drive your boot or root partition is on:\n\nUsually /dev/sda1. Be careful!" 10 70 2> $TMP/bout
                if [ $? = 1 ] || [ $? = 255 ] ; then
                    chroot_menu
                    return 0
                fi
                boot_part=$(cat $TMP/bout)
            fi

            sed -i "s,/dev/sda3,$boot_part,g" /boot/syslinux/syslinux.cfg
            sed -i "s/Arch /mooOS GNU\//g" /boot/syslinux/syslinux.cfg
            sed -i "s,#MENU BACKGROUND splash.png,MENU BACKGROUND /usr/share/moo-tools/images/splash.png,g" /boot/syslinux/syslinux.cfg
            sed -i "s/UI menu.c32/#UI menu.c32/g" /boot/syslinux/syslinux.cfg
            sed -i "s/#UI vesamenu.c32/UI vesamenu.c32/g" /boot/syslinux/syslinux.cfg
            sed -i "s/TIMEOUT 50/TIMEOUT 300/g" /boot/syslinux/syslinux.cfg

            $DIALOG --clear --backtitle "$upper_title" --title "[ SYSLINUX ]" --defaultno --yesno "Edit/view syslinux.cfg?" 10 30
            if [ $? = 0 ] ; then
                nano /boot/syslinux/syslinux.cfg
            fi
            bootmsg="/boot/syslinux/syslinux.cfg @ $boot_part"
        fi
        current_selection 7
    }

    conf_view() {
        echo "HOSTNAME: $(cat /etc/hostname)"
        echo "TIMEZONE: $(readlink /etc/localtime)"
        echo "LOCALE: $(cat /etc/locale.conf)"
        echo "ROOT PASSWORD: $(cat $TMP/rootpasswd)"
        echo "USERS: $(awk -F":" '$7 ~ /\/usr\/bin\/zsh/ {print $1}' /etc/passwd)"
        echo "BOOTLOADER: $bootmsg"
        echo "Returning to menu in 5 seconds..."
        sleep 5s
        $DIALOG --clear --backtitle "$upper_title" --title "[ VIEW CONFIGURATION ]" --msgbox "Return" 10 30
        current_selection 8
    }

    edit_file() {
        $DIALOG --clear --backtitle "$upper_title" --title "[ Edit files ]" --msgbox "Please choose a file to open with nano.\n\nUse the <tab>, <spacebar> and arrow keys to navigate and select file." 10 30

        file_edit=$($DIALOG --stdout --backtitle "$upper_title" --title "Please select file." --fselect /etc/ 0 0)

        if [ $? = 0 ] ; then
            nano "$file_edit"
            $DIALOG --clear --backtitle "$upper_title" --title "[ Edit files ]" --defaultno --yesno "Edit/view another file?" 10 30
            if [ $? = 0 ] ; then
                edit_file
            else
                chroot_menu
                return 0 
            fi
        else
            chroot_menu
            return 0 
        fi
        current_selection 9
    }

  make_internet() {
        $DIALOG --clear --backtitle "$upper_title" --title "Internet" --msgbox "Test/configure internet connection" 10 70
        if [ $? = 255 ] ; then
            chroot_menu
            return 0 
        fi

        $DIALOG --clear --backtitle "$upper_title" --title "Internet" --yesno "Configure wired connection?" 10 70
        if [ $? = 0 ] ; then
            local net_list mynet
            for mynet in $(ip link show | awk '/: / {print $2}' | tr -d :) ; do
                net_list+="${mynet} - "
            done

            my_networks=$($DIALOG --stdout --backtitle "$upper_title" --title 'Internet' --cancel-label "Go Back" \
            --default-item "${my_networks}" --menu "Choose network or <Go Back> to return" 16 45 23 ${net_list} "Exit" "-" || echo "${my_networks}")

            if [ "$my_networks" = "" ] || [ $? = 255 ] || [ "$my_networks" = "Exit" ] ; then
                chroot_menu
                return 0
            fi

            if [ "$my_networks" ] ; then # some better check should be here / placeholder
                dhcpcd $my_networks
                systemctl start dhcpcd
                systemctl enable dhcpcd

                # if [ -f /usr/bin/netctl ]; then
                #     mkdir create_network && cd create_network
                #     wget http://www.opennicproject.org/nearest-servers/
                #     dns_ip1=$(grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' index.html | sort -r | head -1)
                #     dns_ip2=$(grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' index.html | sort -rg | head -1)
                #     cp /etc/netctl/examples/ethernet-static /etc/netctl/ethernetstatic
                #     sed -i "s/eth0/$my_networks/g" /etc/netctl/ethernetstatic
                #     echo "DNS=('$dns_ip1' '$dns_ip2')" >> /etc/netctl/ethernetstatic
                #     netctl start ethernetstatic
                #     netctl enable ethernetstatic
                #     cd .. && rm -r create_network
                # else
                #     dhcpcd $my_networks
                # fi

                $DIALOG --clear --backtitle "$upper_title" --title "Internet" --msgbox "Set network to $my_networks using dhcpcd (enabled/started)" 10 30
            else
                $DIALOG --clear --backtitle "$upper_title" --title "Internet" --msgbox "Failed to set network...network does not exist/null?" 10 30
            fi

            ## TODO sanity checks
        else
            $DIALOG --clear --backtitle "$upper_title" --title "Internet" --radiolist "Choose your preferred wireless setup tool" 10 70 30 \
            "1" "wifi-menu" on \
            "2" "wpa_supplicant" off \
            2> $TMP/pwifi
            if [ $? = 1 ] || [ $? = 255 ] ; then
                chroot_menu
                return 0 
            fi

            local net_list mynet
            for mynet in $(ip link show | awk '/: / {print $2}' | tr -d :) ; do
                net_list+="${mynet} - "
            done

            my_networks=$($DIALOG --stdout --backtitle "$upper_title" --title 'Internet' --cancel-label "Go Back" \
            --default-item "${my_networks}" --menu "Choose network or <Go Back> to return" 16 45 23 ${net_list} "Exit" "-" || echo "${my_networks}")

            if [ "$my_networks" = "" ] || [ $? = 255 ] || [ "$my_networks" = "Exit" ] ; then
                chroot_menu
                return 0
            fi

            if [ "$my_networks" ] ; then # some better check should be here / placeholder
                dhcpcd $my_networks
                $DIALOG --clear --backtitle "$upper_title" --title "Internet" --msgbox "Set network to $my_networks" 10 30
            else
                $DIALOG --clear --backtitle "$upper_title" --title "Internet" --msgbox "Failed to set network...network does not exist/null?" 10 30
            fi

            pwifi=$(cat $TMP/pwifi)
            if [ "$pwifi" == "1" ] ; then
                if [ -f /usr/bin/netctl ]; then
                    wifi-menu $my_networks
                else
                    dhcpcd $my_networks
                fi
            else
                $DIALOG --clear --backtitle "$upper_title" --title "Internet" --inputbox "Please enter your SSID" 10 70 2> $TMP/pssid
                pssid=$(cat $TMP/pssid)

                $DIALOG --clear --backtitle "$upper_title" --title "Internet" --passwordbox "Please enter your wireless passphrase" 10 70 2> $TMP/ppassphrase
                ppassphrase=$(cat $TMP/ppassphrase)
                wpa_passphrase "$pssid" "$ppassphrase" >> /etc/wpa_supplicant.conf
                wpa_supplicant -B -Dwext -i $my_networks -c /etc/wpa_supplicant.conf & >/dev/null
            fi
        fi

        $DIALOG --clear --backtitle "$upper_title" --title "Internet" --msgbox "Internet configuration complete.\n\n Hit enter to return to menu" 10 30
        current_selection 10
    }

    make_mooOS() {
        if [ "$puser" != "" ]; then

            my_home="/home/$puser/"
            dev_directory="${my_home}Github/"

            locale-gen

            if [ ! -f "/var/log/polipo.log" ]; then

                # mkdir -p /usr/share/tor/hidden_service1
                # mkdir -p /usr/share/tor/hidden_service2
                # mkdir -p /usr/share/tor/hidden_service3
                # mkdir -p /usr/share/tor/hidden_service4
                # chown -R tor:tor /usr/share/tor/hidden_service1
                # chown -R tor:tor /usr/share/tor/hidden_service2
                # chown -R tor:tor /usr/share/tor/hidden_service3
                # chown -R tor:tor /usr/share/tor/hidden_service4

                groupadd -r polipo
                useradd -d /var/cache/polipo -g polipo -r -s /bin/false polipo
                touch /var/log/polipo.log
                chown -R polipo:polipo /var/log/polipo.log /var/cache/polipo

                #sh -c "echo .include /usr/lib/systemd/system/polipo.service
    #[Service]
    #User=polipo  > /etc/systemd/system/polipo.service"

                #systemctl enable dhcpcd@eth0.service
                #systemctl enable NetworkManager.service
                #systemctl enable vnstat.sevice
                systemctl disable sshd.service iptables.service cpupower.service
                systemctl enable multi-user.target pacman-init.service
                # choose-mirror.service
                systemctl enable ntpd.service
                systemctl enable tor.service
                systemctl enable privoxy.service
                systemctl enable preload.service
                systemctl enable polipo.service
                systemctl enable cronie.service
                systemctl enable dhcpcd.service

                # $DIALOG --clear --backtitle "$upper_title" --title "Extra" --defaultno --yesno "Install foo and bar?" 10 30

                # if [ $? = 0 ] ; then

                    HOSTNAME="$(cat /etc/hostname)"

                    # #$DIALOG --clear --title "$upper_title" --msgbox "Installing Apache/MySQL/PHP/PHPMyAdmin configuration files" 10 30
                    # mv -v /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.bak
                    # cp -v ${dev_directory}etc/httpd.conf /etc/httpd/conf/httpd.conf
                    # cp -v ${dev_directory}etc/httpd-phpmyadmin.conf /etc/httpd/conf/extra/httpd-phpmyadmin.conf
                    # mv -v /etc/php/php.ini /etc/php/php.ini.bak
                    # cp -v ${dev_directory}etc/php.ini /etc/php/php.ini
                
                    # sh -c "echo '#
                    # # /etc/hosts: static lookup table for host names
                    # #

                    # #<ip-address>  <hostname.domain.org>   <hostname>
                    # 127.0.0.1   localhost.localdomain   localhost $HOSTNAME
                    # ::1      localhost.localdomain   localhost
                    # 127.0.0.1 $puser.c0m www.$puser.c0m
                    # 127.0.0.1 $puser.$HOSTNAME.c0m www.$puser.$HOSTNAME.c0m
                    # 127.0.0.1 phpmyadmin.$puser.c0m www.phpmyadmin.$puser.c0m
                    # 127.0.0.1 torrent.$puser.c0m www.torrent.$puser.c0m
                    # 127.0.0.1 admin.$puser.c0m www.admin.$puser.c0m
                    # 127.0.0.1 stats.$puser.c0m www.stats.$puser.c0m
                    # 127.0.0.1 mail.$puser.c0m www.mail.$puser.c0m

                    # # End of file' > /etc/hosts"

                    # sh -c "echo 'NameVirtualHost *:80
                    # NameVirtualHost *:444

                    # #this first virtualhost enables: http://127.0.0.1, or: http://localhost, 
                    # #to still go to /srv/http/*index.html(otherwise it will 404_error).
                    # #the reason for this: once you tell httpd.conf to include extra/httpd-vhosts.conf, 
                    # #ALL vhosts are handled in httpd-vhosts.conf(including the default one),
                    # # E.G. the default virtualhost in httpd.conf is not used and must be included here, 
                    # #otherwise, only domainname1.dom & domainname2.dom will be accessible
                    # #from your web browser and NOT http://127.0.0.1, or: http://localhost, etc.
                    # #

                    # <VirtualHost *:80>
                    # DocumentRoot \"/srv/http/root\"
                    # ServerAdmin root@localhost
                    # #ErrorLog \"/var/log/httpd/127.0.0.1-error_log\"
                    # #CustomLog \"/var/log/httpd/127.0.0.1-access_log\" common
                    # <Directory /srv/http/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:444>
                    # DocumentRoot \"/srv/http/root\"
                    # ServerAdmin root@localhost
                    # #ErrorLog \"/var/log/httpd/127.0.0.1-error_log\"
                    # #CustomLog \"/var/log/httpd/127.0.0.1-access_log\" common
                    # <Directory /srv/http/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:80>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/$puser.c0m/public_html\"
                    # ServerName $puser.c0m
                    # ServerAlias $puser.c0m www.$puser.c0m
                    # <Directory /srv/http/$puser.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:444>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/$puser.c0m/public_html\"
                    # ServerName $puser.c0m
                    # ServerAlias $puser.c0m www.$puser.c0m
                    # <Directory /srv/http/$puser.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:80>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/$puser.$HOSTNAME.c0m/public_html\"
                    # ServerName $puser.$HOSTNAME.c0m
                    # ServerAlias $puser.$HOSTNAME.c0m www.$puser.$HOSTNAME.c0m
                    # <Directory /srv/http/$puser.$HOSTNAME.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:444>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/$puser.$HOSTNAME.c0m/public_html\"
                    # ServerName $puser.$HOSTNAME.c0m
                    # ServerAlias $puser.$HOSTNAME.c0m www.$puser.$HOSTNAME.c0m
                    # <Directory /srv/http/$puser.$HOSTNAME.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:80>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/usr/share/webapps/phpMyAdmin\"
                    # ServerName phpmyadmin.$puser.c0m
                    # ServerAlias phpmyadmin.$puser.c0m www.phpmyadmin.$puser.c0m
                    # <Directory /usr/share/webapps/phpMyAdmin/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:444>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/usr/share/webapps/phpMyAdmin\"
                    # ServerName phpmyadmin.$puser.c0m
                    # ServerAlias phpmyadmin.$puser.c0m www.phpmyadmin.$puser.c0m
                    # <Directory /usr/share/webapps/phpMyAdmin/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:80>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/torrent.$puser.c0m/public_html\"
                    # ServerName torrent.$puser.c0m
                    # ServerAlias torrent.$puser.c0m www.torrent.$puser.c0m
                    # <Directory /srv/http/torrent.$puser.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:444>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/torrent.$puser.c0m/public_html\"
                    # ServerName torrent.$puser.c0m
                    # ServerAlias torrent.$puser.c0m www.torrent.$puser.c0m
                    # <Directory /srv/http/torrent.$puser.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:80>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/admin.$puser.c0m/public_html\"
                    # ServerName admin.$puser.c0m
                    # ServerAlias admin.$puser.c0m www.admin.$puser.c0m
                    # <Directory /srv/http/admin.$puser.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:444>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/admin.$puser.c0m/public_html\"
                    # ServerName admin.$puser.c0m
                    # ServerAlias admin.$puser.c0m www.admin.$puser.c0m
                    # <Directory /srv/http/admin.$puser.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:80>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/stats.$puser.c0m/public_html\"
                    # ServerName stats.$puser.c0m
                    # ServerAlias stats.$puser.c0m www.stats.$puser.c0m
                    # <Directory /srv/http/stats.$puser.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:444>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/stats.$puser.c0m/public_html\"
                    # ServerName stats.$puser.c0m
                    # ServerAlias stats.$puser.c0m www.stats.$puser.c0m
                    # <Directory /srv/http/stats.$puser.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:80>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/mail.$puser.c0m/public_html\"
                    # ServerName mail.$puser.c0m
                    # ServerAlias mail.$puser.c0m www.mail.$puser.c0m
                    # <Directory /srv/http/mail.$puser.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>

                    # <VirtualHost *:444>
                    # ServerAdmin $puser@$HOSTNAME
                    # DocumentRoot \"/srv/http/mail.$puser.c0m/public_html\"
                    # ServerName mail.$puser.c0m
                    # ServerAlias mail.$puser.c0m www.mail.$puser.c0m
                    # <Directory /srv/http/mail.$puser.c0m/public_html/>
                    # DirectoryIndex index.htm index.html
                    # AddHandler cgi-script .cgi .pl
                    # Options ExecCGI Indexes FollowSymLinks MultiViews +Includes
                    # AllowOverride None
                    # Order allow,deny
                    # allow from all
                    # </Directory>
                    # </VirtualHost>' > /etc/httpd/conf/extra/httpd-vhosts.conf"

                    # echo sh -c "echo '#
                    # # /etc/hosts: static lookup table for host names
                    # #

                    # #<ip-address>  <hostname.domain.org>   <hostname>
                    # 127.0.0.1   localhost.localdomain   localhost $HOSTNAME
                    # ::1      localhost.localdomain   localhost
                    # 127.0.0.1 $puser.c0m www.$puser.c0m
                    # 127.0.0.1 $puser.$HOSTNAME.c0m www.$puser.$HOSTNAME.c0m
                    # 127.0.0.1 phpmyadmin.$puser.c0m www.phpmyadmin.$puser.c0m
                    # 127.0.0.1 torrent.$puser.c0m www.torrent.$puser.c0m
                    # 127.0.0.1 admin.$puser.c0m www.admin.$puser.c0m
                    # 127.0.0.1 stats.$puser.c0m www.stats.$puser.c0m
                    # 127.0.0.1 mail.$puser.c0m www.mail.$puser.c0m

                    # # End of file' > /etc/hosts"

                    # #TODO
                    # # $DIALOG --clear --backtitle "$upper_title" --title "Extra" --msgbox "Creating self-signed certificate" 10 30
                    # cd /etc/httpd/conf
                    # openssl genrsa -des3 -out server.key 1024
                    # openssl req -new -key server.key -out server.csr
                    # cp -v server.key server.key.org
                    # openssl rsa -in server.key.org -out server.key
                    # openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

                    # mkdir -p /srv/http/root/public_html
                    # chmod g+xr-w /srv/http/root
                    # chmod -R g+xr-w /srv/http/root/public_html

                    # mkdir -p /srv/http/$puser.c0m/public_html
                    # chmod g+xr-w /srv/http/$puser.c0m
                    # chmod -R g+xr-w /srv/http/$puser.c0m/public_html

                    # mkdir -p /srv/http/$puser.$HOSTNAME.c0m/public_html
                    # chmod g+xr-w /srv/http/$puser.$HOSTNAME.c0m
                    # chmod -R g+xr-w /srv/http/$puser.$HOSTNAME.c0m/public_html

                    # mkdir -p /srv/http/phpmyadmin.$puser.c0m/public_html
                    # chmod g+xr-w /srv/http/phpmyadmin.$puser.c0m
                    # chmod -R g+xr-w /srv/http/phpmyadmin.$puser.c0m/public_html

                    # mkdir -p /srv/http/torrent.$puser.c0m/public_html
                    # chmod g+xr-w /srv/http/torrent.$puser.c0m
                    # chmod -R g+xr-w /srv/http/torrent.$puser.c0m/public_html

                    # mkdir -p /srv/http/admin.$puser.c0m/public_html
                    # chmod g+xr-w /srv/http/admin.$puser.c0m
                    # chmod -R g+xr-w /srv/http/admin.$puser.c0m/public_html

                    # mkdir -p /srv/http/stats.$puser.c0m/public_html
                    # chmod g+xr-w /srv/http/stats.$puser.c0m
                    # chmod -R g+xr-w /srv/http/stats.$puser.c0m/public_html

                    # mkdir -p /srv/http/mail.$puser.c0m/public_html
                    # chmod g+xr-w /srv/http/mail.$puser.c0m
                    # chmod -R g+xr-w /srv/http/mail.$puser.c0m/public_html

                    #     systemctl start httpd
                    #     systemctl start mysqld
                    #     sleep 1s
                    #     $DIALOG --clear --backtitle "$upper_title" --title "mooOS" --msgbox "Ok... starting MySQL and setting a root password for MySQL...." 10 30
                    #     rand=$RANDOM
                    #     mysqladmin -u root password $puser-$rand
                    #     $DIALOG --backtitle "$upper_title" --title "Extra" --msgbox "You're mysql root password is $puser-$rand\nWrite this down before proceeding..." 10 30
                    #     $DIALOG --backtitle "$upper_title" --title "Extra" --msgbox "If you want to change/update the above root password (AT A LATER TIME), then you need to use the following command:\n$ mysqladmin -u root -p'$puser-$rand' password newpasswordhere\nFor example, you can set the new password to 123456, enter:\n$ mysqladmin -u root -p'$puser-$rand' password '123456'" 20 40
                    #     ln -s /usr/share/webapps/phpMyAdmin /srv/http/phpmyadmin.$puser.c0m
                    #     ln -s /srv/http ${my_home}localhost
                    #     chown -R $puser /srv/http

                    #     $DIALOG --clear --backtitle "$upper_title" --title "Extra" --msgbox "Your LAMP setup is set to be started manually via the Awesome menu->Services-> LAMP On/Off" 10 30

                    #     $DIALOG --clear --backtitle "$upper_title" --title "Extra" --msgbox "If you want LAMP to start at boot, run these commands ay any time as root user:\n\nsystemctl enable httpd.service\nsystemctl enable mysqld.service\nsystemctl enable memcached.service" 10 40
                        
                    #     $DIALOG --clear --backtitle "$upper_title" --title "Extra" --yesno "Do you want this to be done now? [default=No]?" 10 30
                    #     if [ $? = 0 ] ; then
                    #         systemctl enable httpd.service
                    #         systemctl enable mysqld.service
                    #         systemctl enable memcached.service
                    #     fi
                       #echo "nothing done, placeholder - ask pdq"
                       #sleep 3s
                    #fi

                    squid -z &
                    systemctl daemon-reload
                    sed -i "s/moo/$puser/g" /etc/systemd/system/getty@tty1.service.d/autologin.conf
                    sed -i "s/moo/$puser/g" /etc/systemd/system/autologin@.service
                    sed -i "s/moo/$puser/g" /etc/systemd/system/transmission.service
                    sed -i "s/moo/$puser/g" /etc/psd.conf

                    sed -i "s/alice/$GEN_HOSTNAME/g" /etc/squid/squid.conf
                    chmod -R 777 /run/transmission
                    chown -R $puser /run/transmission
                    
                    PWD=$(pwd)
                    ## patch config files for username
                    cd /home/$puser/.e/e/config/standard
                    for NEW_FILE in e.*
                    do
                        EWW_FILE=${NEW_FILE/.cfg/.src}

                        su $puser -c "eet -d $NEW_FILE config $EWW_FILE"
                        su $puser -c "sed -i \"s/moo/$puser/g\" $EWW_FILE"
                        rm $NEW_FILE
                        su $puser -c "eet -e $NEW_FILE config $EWW_FILE 1"
                        rm $EWW_FILE
                    done
                    cd $PWD

                    ## clean up files content
                    su $puser -c "sed -i \"s/moo/$puser/g\" /home/$puser/.mozilla/firefox/qrtww0pl.Default-User/extensions.ini"
                    su $puser -c "sed -i \"s/moo/$puser/g\" /home/$puser/.config/transmission-daemon/settings.json"
                    su $puser -c "sed -i \"s/moo/$puser/g\" /home/$puser/.moc/config"
                    su $puser -c "sed -i \"s/moo/$puser/g\" /home/$puser/.kde4/share/config/dolphinrc"
                    su $puser -c "sed -i \"s/moo/$puser/g\" /home/$puser/.gtkrc-2.0"

                    # su $puser -c "vb \"https://wiki.archlinux.org/index.php/Installation_Guide#Video_driver\" &"
                    # $DIALOG --clear --backtitle "$upper_title" --title "Video Driver" --defaultno --yesno "Do you wish to install a video driver now?" 20 70
                    # if [ $? = 0 ] ; then
                    #     su $puser -c "urxvt -name 'Video Driver' -title 'Video Driver' -e"
                    # fi

                    # $DIALOG --clear --backtitle "$upper_title" --title "mooOS" --yesno "Enable automatic login to virtual console?" 10 30
                    # if [ $? = 0 ] ; then
                    #     systemctl disable getty@tty1
                    #     systemctl enable autologin@tty1
                    #     systemctl start autologin@tty1
                    # fi
                    
                    # not needed anymore since zsh shell is set via chroot script run previously
                    # $DIALOG --clear --backtitle "$upper_title" --title "mooOS" --msgbox "Ok, setup is complete... the next screen will prompt you for your user password..." 10 40
                    # chsh -s $(which zsh)

              #       if [ "$archtype" = "x86_64" ]; then
              #       $DIALOG --clear --backtitle "$upper_title" --title "mooOS" --msgbox "exiting install script...\n\nIf complete, type: sudo reboot (you may also want to search, chose and install a video driver now.\n\npacaur XXXX\n\nReplacing XXXX with:\n'lib32-ati-dri: for open source ATI driver users'
              # 'lib32-catalyst-utils: for AMD Catalyst users'
              # 'lib32-intel-dri: for open source Intel driver users'
              # 'lib32-nouveau-dri: for Nouveau users'
              # 'lib32-nvidia-utils-bumblebee: for NVIDIA + Bumblebee users'
              # 'lib32-nvidia-utils: for NVIDIA proprietary blob users'" 30 70
                  #  else
              fi
                $DIALOG --clear --backtitle "$upper_title" --title "mooOS" --msgbox "Exiting install script...." 30 70
               # fi
            #fi

        fi
        current_selection 11
    }

    chroot_menu() {
        #echo "make it so"
        rootpasswd=$(cat $TMP/rootpasswd)
        CUR=$(cat $_CCURRENT)
        $DIALOG \
            --default-item "$CUR" --colors --backtitle "$upper_title" --title "mooOS Installer (chroot)" \
            --menu "Select action:" 20 60 11 \
            1 $clr"Generate hostname [${GEN_HOSTNAME}]"$clr_end \
            2 $clr"Generate timezone [${GEN_TIMEZONE}]"$clr_end \
            3 $clr"Generate locale [${GEN_LANG}]"$clr_end \
            4 $clr"Set root password [$rootpasswd]"$clr_end \
            5 $clr"Create default user and add to sudoers"$clr_end \
            6 $clr"Install Bootloader"$clr_end \
            7 $clr"View/confirm generated data"$clr_end \
            8 $clr"View/edit files [optional]"$clr_end \
            9 $clr"Set up Network [mandatory]"$clr_end \
            10 $clr"Tidy up Install"$clr_end \
            11 $clr"Return to Installer"$clr_end 2>$_TEMP

        if [ $? = 1 ] || [ $? = 255 ] ; then
            exiting
            return 0
        fi

        choice=$(cat $_TEMP)
        case $choice in
            1) gen_hostname;;
            2) gen_tz;;
            3) gen_locale;;
            4) set_root_pass;;
            5) add_user;;
            6) install_bootloader;;
            7) conf_view;;
            8) edit_file;;
            9) make_internet;;
            10) make_mooOS;;
            11) exiting;;
        esac
    }

    # utility execution
    while true
    do
        chroot_menu
    done
fi

exit 0